// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSzUXbQV5Z2-psxdjITf1XNtCyFjnWm34',
    appId: '1:1060161913171:android:af73c28cf1b003f555a1a6',
    messagingSenderId: '1060161913171',
    projectId: 'flutter-bond-staging',
    storageBucket: 'flutter-bond-staging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkWff8DcTgZEC62yTSak6B9p2Y4JQ8_Jg',
    appId: '1:1060161913171:ios:7e71769f5507f2b255a1a6',
    messagingSenderId: '1060161913171',
    projectId: 'flutter-bond-staging',
    storageBucket: 'flutter-bond-staging.appspot.com',
    iosClientId: '1060161913171-8alevp0lf0e1cnen8srld97p26lculii.apps.googleusercontent.com',
    iosBundleId: 'ps.app.bond.staging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkWff8DcTgZEC62yTSak6B9p2Y4JQ8_Jg',
    appId: '1:1060161913171:ios:a2ddfea873792ada55a1a6',
    messagingSenderId: '1060161913171',
    projectId: 'flutter-bond-staging',
    storageBucket: 'flutter-bond-staging.appspot.com',
    iosClientId: '1060161913171-81tqkgkcqusecm5mv2qu1a6n0kcusjb6.apps.googleusercontent.com',
    iosBundleId: 'ps.app.flutterBond.staging',
  );
}
