// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLLbGUsCyPReodUJZ6GIKNzehzJ0OQCnE',
    appId: '1:1060161913171:web:68b14b55cce605b655a1a6',
    messagingSenderId: '1060161913171',
    projectId: 'flutter-bond-staging',
    authDomain: 'flutter-bond-staging.firebaseapp.com',
    storageBucket: 'flutter-bond-staging.appspot.com',
    measurementId: 'G-FF63T3YF4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-AjzVELSPttuIp2k6kydk0RX-DORqPpg',
    appId: '1:390157281889:android:bf4d85c3c9a51044ab9820',
    messagingSenderId: '390157281889',
    projectId: 'flutter-bond-staging-7dd42',
    storageBucket: 'flutter-bond-staging-7dd42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz95QyOlPlhPWZFUrduUsS5Q8g5boiQgc',
    appId: '1:390157281889:ios:8c87b8875dcdd94aab9820',
    messagingSenderId: '390157281889',
    projectId: 'flutter-bond-staging-7dd42',
    storageBucket: 'flutter-bond-staging-7dd42.appspot.com',
    iosBundleId: 'ps.app.bond.staging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz95QyOlPlhPWZFUrduUsS5Q8g5boiQgc',
    appId: '1:390157281889:ios:ba7ec93993371072ab9820',
    messagingSenderId: '390157281889',
    projectId: 'flutter-bond-staging-7dd42',
    storageBucket: 'flutter-bond-staging-7dd42.appspot.com',
    iosBundleId: 'ps.app.flutterBond.staging',
  );

}