// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfL8g3p3PmS3kUNPDxn5_RaKKDmFcZKKw',
    appId: '1:766000556009:android:5a55ed668d929522d0cd78',
    messagingSenderId: '766000556009',
    projectId: 'flutter-bond-87485',
    storageBucket: 'flutter-bond-87485.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVvGOc_wPjffCwxy9BlL5kweFhp7-rfYg',
    appId: '1:766000556009:ios:c008c663168299bed0cd78',
    messagingSenderId: '766000556009',
    projectId: 'flutter-bond-87485',
    storageBucket: 'flutter-bond-87485.appspot.com',
    iosClientId: '766000556009-0u0bfplre3qmoe13fq7imp8e6528e4af.apps.googleusercontent.com',
    iosBundleId: 'ps.app.bond',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVvGOc_wPjffCwxy9BlL5kweFhp7-rfYg',
    appId: '1:766000556009:ios:0106a631aa70de18d0cd78',
    messagingSenderId: '766000556009',
    projectId: 'flutter-bond-87485',
    storageBucket: 'flutter-bond-87485.appspot.com',
    iosClientId: '766000556009-or1qj1cqpll0vl08qshde7p68fjhe9bh.apps.googleusercontent.com',
    iosBundleId: 'ps.app.flutterBond.staging',
  );
}
